// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ObjectMap;
import helpers.AxeMain;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ObjectMap</b><br>
 * Generated     : <b>2011/11/21 8:14:14 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  November 21, 2011
 * @author Jaco
 */
public abstract class ObjectMapHelper extends helpers.AxeMain
{
	/**
	 * VehicleRepaymentCalculator: with default state.
	 *		.title : Vehicle Repayment Calculator
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.wesbank.co.za/WesBankCoZa/calculators/vehiclerepayment/index.jspx?si ...
	 */
	public DocumentTestObject FinQuoteHome() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("FinQuoteHome"));
	}
	/**
	 * VehicleRepaymentCalculator: with specific test context and state.
	 *		.title : Vehicle Repayment Calculator
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.wesbank.co.za/WesBankCoZa/calculators/vehiclerepayment/index.jspx?si ...
	 */
	public DocumentTestObject FinQuoteHome(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("FinQuoteHome"), anchor, flags);
	}
	
	/**
	 * Calculatebutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Calculate
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject FinQuoteHome_btncalculatebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("FinQuoteHome_btncalculatebutton"));
	}
	/**
	 * Calculatebutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Calculate
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public GuiTestObject FinQuoteHome_btncalculatebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("FinQuoteHome_btncalculatebutton"), anchor, flags);
	}
	
	/**
	 * ClearFormbutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Clear form
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject FinQuoteHome_btnclearForm() 
	{
		return new GuiTestObject(
                        getMappedTestObject("FinQuoteHome_btnclearForm"));
	}
	/**
	 * ClearFormbutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Clear form
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	public GuiTestObject FinQuoteHome_btnclearForm(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("FinQuoteHome_btnclearForm"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	public GuiTestObject FinQuoteHome_btnOkButton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("FinQuoteHome_btnOkButton"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	public GuiTestObject FinQuoteHome_btnOkButton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("FinQuoteHome_btnOkButton"), anchor, flags);
	}
	
	/**
	 * MessageFromWebpage: with default state.
	 *		.text : Message from webpage
	 * 		.class : WinError
	 * 		.processName : iexplore.exe
	 * 		.name : Message from webpage
	 */
	public TopLevelSubitemTestObject FinQuoteHome_msgErrorwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("FinQuoteHome_msgErrorwindow"));
	}
	/**
	 * MessageFromWebpage: with specific test context and state.
	 *		.text : Message from webpage
	 * 		.class : WinError
	 * 		.processName : iexplore.exe
	 * 		.name : Message from webpage
	 */
	public TopLevelSubitemTestObject FinQuoteHome_msgErrorwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("FinQuoteHome_msgErrorwindow"), anchor, flags);
	}
	
	/**
	 * _0: with default state.
	 *		.id : finDeposit
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	public TextGuiTestObject FinQuoteHome_txtDeposit() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FinQuoteHome_txtDeposit"));
	}
	/**
	 * _0: with specific test context and state.
	 *		.id : finDeposit
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	public TextGuiTestObject FinQuoteHome_txtDeposit(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FinQuoteHome_txtDeposit"), anchor, flags);
	}
	
	/**
	 * _20114000: with default state.
	 *		.id : finLoan
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	public TextGuiTestObject FinQuoteHome_txtFinAmount() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FinQuoteHome_txtFinAmount"));
	}
	/**
	 * _20114000: with specific test context and state.
	 *		.id : finLoan
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	public TextGuiTestObject FinQuoteHome_txtFinAmount(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FinQuoteHome_txtFinAmount"), anchor, flags);
	}
	
	/**
	 * calcformFinPrice: with default state.
	 *		.id : calcform:finPrice
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : calcform:finPrice
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject FinQuoteHome_txtPurPrice() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FinQuoteHome_txtPurPrice"));
	}
	/**
	 * calcformFinPrice: with specific test context and state.
	 *		.id : calcform:finPrice
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : calcform:finPrice
	 * 		.classIndex : 0
	 */
	public TextGuiTestObject FinQuoteHome_txtPurPrice(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FinQuoteHome_txtPurPrice"), anchor, flags);
	}
	
	/**
	 * _0: with default state.
	 *		.id : finExtras
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public TextGuiTestObject FinQuoteHome_txtValExtras() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FinQuoteHome_txtValExtras"));
	}
	/**
	 * _0: with specific test context and state.
	 *		.id : finExtras
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	public TextGuiTestObject FinQuoteHome_txtValExtras(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FinQuoteHome_txtValExtras"), anchor, flags);
	}
	
	

	protected ObjectMapHelper()
	{
		setScriptName("ObjectMap.ObjectMap");
	}
	
}

